name: Silver Treasure Artisan Duster Long
styleId: 570125284
description: |
    <p>The long jacket layer to fall in love with thanks to our supple velvet, romantic lace rhinestone button front placket. Stand collar.</p>
    <ul>
        <li>Stand collar.</li>
        <li>Length: 30+".</li>
        <li>93% cotton, 5% metallic, 2% polyester.</li>
        <li>Imported.</li>
    </ul>
color: 3582
colorName: Mountain Smoke
price: $129.00
priceSale: $77.40

styleID2: 570132139
color2: 1014
colorName2: Anguilla

